const data ={
    products:[
        {
        id:"1",
        name: "cukur",
        slug: "MR-Book",
        category: "Book",
        image: "https://mokabook.net/wp-content/uploads/2022/08/1648449598_front-cover-alhofura.png",
        price: 20,
        countInStock: 20,
        rating: 5,
        numReview: 10,
        desecription: "high quality product",
    },
    {
        id:"2",
        name: "The Woman In Black",
        slug: "دار دوّن للنشر والتوزيع",
        category: "Book",
        image: "https://cdn.shopify.com/s/files/1/0385/8490/9956/products/83_d516085a-c286-49cd-b335-ac0fca137e29_800x.webp?v=1661775087",
        price: 8,
        countInStock: 16,
        rating: 4,
        numReview: 8,
        desecription: "high quality product",
    },
    {
        id:"3",
        name: "السمراء المنكود",
        slug: "iBookCast",
        category: "Book",
        image: "https://www.ibookcast.com/books-cover/%D8%BA%D9%84%D8%A7%D9%81_%D8%A7%D9%84%D8%B3%D9%85%D8%B1%D8%A7-%D8%A7%D9%84%D9%85%D9%86%D9%83%D9%88%D8%AF.png",
        price: 10,
        countInStock: 11,
        rating: 4.5,
        numReview: 8,
        desecription: "high quality product",
    },
    {
        id:"4",
        name: "فتاة الياقة الزرقاء",
        slug: "كتب الروايات والقصص",
        category: "Book",
        image: "https://books-library.website/files/books-library.net-07121241Nl2C1.jpg",
        price: 12,
        countInStock: 11,
        rating: 4.5,
        numReview: 10,
        desecription: "high quality product",
    },
    {
        id:"5",
        name: "سقطرى",
        slug: "Ibook",
        category: "Book",
        image: "https://books-library.com/files/books-library.com-11141547Jq5T3.jpg",
        price: 7,
        countInStock: 4,
        rating: 3.5,
        numReview: 10,
        desecription: "high quality product",
    },
    {
        id:"6",
        name: "كن مع الشخص الذي يجعلك سعيدا",
        slug: "Ibook",
        category: "Book",
        image: "https://cdn.shopify.com/s/files/1/0385/8490/9956/products/6_080dfe5c-c930-4705-8919-9d148c07983d_800x.png?v=1642078334",
        price: 11,
        countInStock: 4,
        rating: 4,
        numReview: 10,
        desecription: "high quality product",
    },
],
}

export default data ;


// const data ={
//     products:[
//         {
//         name: "Nike slim T-shirt",
//         slug: "nike-slim-shirt",
//         category: "Shirts",
//         image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/70ebb896-f02e-40e1-99bd-382f0138cefb/pro-dri-fit-mens-slim-fit-short-sleeve-top-H7B5f3.png",
//         price: 100,
//         countInStock: 20,
//         brand: "Nike",
//         rating: 4.5,
//         numReview: 10,
//         desecription: "high quality product",
//     },
//     {
//         name: "Jacket",
//         slug: "H&M Jacket",
//         category: "Jacket",
//         image: "https://cdn.shopify.com/s/files/1/1364/2823/products/BUZZARD3_0fdce575-4cdf-47c3-a963-9731f04d6ad9_1080x.jpg?v=1602722180",
//         price: 150,
//         countInStock: 8,
//         brand: "H&M",
//         rating: 5,
//         numReview: 15,
//         desecription: "high quality product",
//     },
//     {
//         name: "Adidas Fit Pant",
//         slug: "Adidas Fit Pant",
//         category: "Pants",
//         image: "https://images.asos-media.com/products/adidas-originals-adicolor-three-stripe-skinny-joggers-in-black-black/14659230-1-black?$n_640w$&wid=513&fit=constrain",
//         price: 75,
//         countInStock: 7,
//         brand: "Adidas",
//         rating: 4.5,
//         numReview: 15,
//         desecription: "high quality product",
//     },
//     {
//         name: "Jacket",
//         slug: "H&MJacket",
//         category: "Jacket",
//         image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/b9/P00702797.jpg",
//         price: 120,
//         countInStock: 17,
//         brand: "H&M",
//         rating: 4.5,
//         numReview: 10,
//         desecription: "high quality product",
//     },
//     {
//         name: "Jacket",
//         slug: "H&M-Jacket",
//         category: "Jacket",
//         image: "https://is4.revolveassets.com/images/p4/n/z/LCDE-WO170_V1.jpg",
//         price: 200,
//         countInStock: 12,
//         brand: "H&M",
//         rating: 4.5,
//         numReview: 12,
//         desecription: "high quality product",
//     },
//     {
//         name: "Nike Training Dri-FIT",
//         slug: "Nike Training Dri-FIT",
//         category: "Shirts",
//         image: "https://images.asos-media.com/products/nike-training-dri-fit-chest-swoosh-t-shirt-in-red/202972006-1-red?$n_750w$&wid=750&fit=constrain",
//         price: 100,
//         countInStock: 20,
//         brand: "Nike",
//         rating: 4.5,
//         numReview: 10,
//         desecription: "high quality product",
//     },
//     {
//         name: "Puma Fit Pant",
//         slug: "Puma Fit Pant",
//         category: "Pants",
//         image: "https://images.asos-media.com/products/puma-essentials-small-logo-joggers-in-khaki/204140419-1-khaki?$n_640w$&wid=513&fit=constrain",
//         price: 75,
//         countInStock: 7,
//         brand: "Puma",
//         rating: 4.5,
//         numReview: 15,
//         desecription: "high quality product",
//     },
// ],
// }

// export default data ;